server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: exchange-rate-service
  threads:
    virtual:
      enabled: true
  task:
    execution:
      pool:
        core-size: 5
        max-size: 20
        queue-capacity: 100
        keep-alive: 60s
      thread-name-prefix: "async-task-"
      shutdown:
        await-termination: true
        await-termination-period: 30s
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  cache:
    type: redis
    redis:
      time-to-live: 2s
      cache-null-values: false
      key-prefix: "fx:"
      use-key-prefix: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
    time-zone: UTC

logging:
  level:
    com.hasandag: INFO
    org.springframework.web: INFO
    org.apache.hc: INFO

springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  default-produces-media-type: application/json

exchange:
  api:
    url: ${EXCHANGE_API_URL:https://open.er-api.com/v6/latest}
  webclient:
    connect-timeout: 10s
    read-timeout: 10s
    write-timeout: 10s
    response-timeout: 15s
  virtual-threads:
    connect-timeout: 5s
    read-timeout: 30s
  client:
    max-attempts: 5
    backoff-delay-ms: 500
    backoff-multiplier: 2.0
    max-delay-ms: 30000
    jitter-factor: 0.15
    rate-limit-status-code: 429
    circuit-breaker-enabled: true
    circuit-breaker-failure-threshold: 5
    circuit-breaker-timeout-ms: 60000
    circuit-breaker-min-calls: 3
  retry:
    scheduler:
      threads: 2
  user-agent:
    default: "Exchange-Rate-Service/1.0"
    virtual-threads: "Exchange-Rate-Service-VirtualThreads/1.0"

external-services:
  virtual-threads:
    enabled: true
    pool-size: 50
    timeout: 30s
  executors:
    external-service:
      thread-name-prefix: "external-service-"
      thread-name-counter: 0
      core-pool-size-factor: 0.5
      queue-capacity-factor: 2.0
    third-party-api:
      thread-name-prefix: "third-party-api-"
      thread-name-counter: 0
      core-pool-size: 10
      max-pool-size: 25
      queue-capacity: 50
    http-client:
      thread-name-prefix: "http-client-"
      thread-name-counter: 0
      core-pool-size: 15
      max-pool-size: 30
      queue-capacity: 100